(() => {
'use strict';
const D=window.CourseData,C=window.SCIENCE_CONFIG,$=s=>document.querySelector(s),app=$('#app');
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const shuffle=a=>{a=[...a];for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;};
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f;}catch{return f;}};
const write=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v));}catch{toast('此瀏覽器無法保存進度，請勿關閉頁面。');}};
let state=read('science-state',null),queue=read('science-queue',[]),page='',draft={},orders={},feedback={},quizStart=Date.now(),timer=null,teacher=false,challengeRun=null,rescueRun=null,flashRun=null,sending=false;
function toast(t){$('#toast').textContent=t;$('#toast').style.display='block';clearTimeout(toast.t);toast.t=setTimeout(()=>$('#toast').style.display='none',4500);}
function newState(identity){return {identity,session:crypto.randomUUID(),token:crypto.randomUUID(),completed:{home:true},answers:{},counts:{},points:{},flash:false,formative:null,rescueFirst:null,rescueBest:0,challengeFirst:null,challengeBest:0};}
function total(){return Object.values(state?.points||{}).reduce((a,b)=>a+b,0);}
function save(){write('science-state',state);}
function emit(kind,detail={}){if(!state)return;const e={requestId:crypto.randomUUID(),courseId:C.courseId,session:state.session,token:state.token,identity:{...state.identity},kind,detail,clientTime:new Date().toISOString()};queue.push(e);write('science-queue',queue);sync();}
function same(a,b){if(Array.isArray(b))return Array.isArray(a)&&a.length===b.length&&([...a].sort().join('|')===[...b].sort().join('|'));if(b&&typeof b==='object')return a&&Object.keys(b).every(k=>a[k]===b[k]);return String(a)===String(b);}
function grade(q,a){if(q.type==='number')return a!==''&&a!==null&&a!==undefined&&Number.isFinite(Number(a))&&Number(a)===Number(q.answer);if(q.type==='order')return Array.isArray(a)&&a.join('|')===q.answer.join('|');return same(a,q.answer);}
function filled(q,a){if(q.type==='multi')return Array.isArray(a)&&a.length>0;if(q.type==='order')return Array.isArray(a)&&a.length===q.options.length;if(['match','classify'].includes(q.type))return a&&q.options.every(o=>a[o.id]);return a!==undefined&&a!==null&&a!=='';}
window.ScienceCore={grade,filled,shuffle};
function requireStudent(){if(state)return true;toast('請先填寫班級、座號與姓名，再開始學習。');location.hash='home';return false;}
function complete(id){if(!state)return;state.completed[id]=true;save();emit('progress',{page:id});renderMap();}
function pageReady(id){if(D.lessons[id])return D.lessons[id].questions.every(q=>state?.answers[q.id])&&(id!=='life'||state?.flash);return !!state?.completed[id];}
function isUnlocked(i){return C.freeNavigation||teacher||i===0||!!state?.completed[D.pages[i-1][0]];}
function renderMap(){const index=D.pages.findIndex(p=>p[0]===page);$('#map').innerHTML=D.pages.map((p,i)=>`<button data-page="${p[0]}" ${isUnlocked(i)?'':'disabled'} class="${p[0]===page?'active':''}" ${p[0]===page?'aria-current="page"':''}><span class="circle">${state?.completed[p[0]]?'✓':isUnlocked(i)?i+1:'🔒'}</span>${p[1]}</button>`).join('');$('#map').querySelectorAll('button').forEach(b=>b.onclick=()=>location.hash=b.dataset.page);$('#map .active')?.scrollIntoView({block:'nearest',inline:'center'});}
function footerNav(){const i=D.pages.findIndex(p=>p[0]===page),can=C.freeNavigation||teacher||pageReady(page);return `<div class="nav-end"><button data-nav="home">回到首頁</button>${i>0?`<button data-nav="${D.pages[i-1][0]}">上一頁</button>`:''}${i<9?`<button class="primary" data-nav="${D.pages[i+1][0]}" ${can?'':'disabled'}>下一頁：${D.pages[i+1][2]} →</button>`:''}</div>${!can?'<p class="small muted">完成本頁活動後，即可前往下一頁。</p>':''}`;}
function title(t,s=''){return `<h1>${t}</h1>${s?`<p class="subtitle">${s}</p>`:''}`;}
function bindCommon(){app.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>location.hash=b.dataset.nav);app.querySelectorAll('img[data-zoom]').forEach(im=>im.onclick=()=>{$('#zoom img').src=im.src;$('#zoom img').alt=im.alt;$('#zoom').showModal();});}
function route(){clearInterval(timer);timer=null;challengeRun=null;rescueRun=null;draft={};orders={};feedback={};flashRun=null;quizStart=Date.now();let id=location.hash.slice(1)||'home';if(!D.pages.some(p=>p[0]===id))id='home';const i=D.pages.findIndex(p=>p[0]===id);if(!isUnlocked(i))id='home';page=id;renderMap();render();window.scrollTo({top:0});}
function render(){if(page==='home')home();else if(D.lessons[page])lesson();else if(page==='assessment')assessment();else if(page==='rescue')rescue();else if(page==='challenge')challenge();else results();bindCommon();}
function home(){const ident=state?.identity||{};app.innerHTML=title('生命探索站','生命的特性與大小世界')+`<section class="card soft hero"><div><h2>從一顆種子，<br>走進看不見的生命世界。</h2><p>用觀察與實驗找證據，完成五個探索任務。</p><p class="small">約兩次自學時間 · 可以隨時停下，下次繼續</p></div><figure><h3>從肉眼到微觀</h3><img src="assets/eye-bacteria.png" alt="卡通眼睛透過箭頭指向放大示意的細菌"><figcaption class="small muted">眼睛 → 細菌（放大示意）</figcaption></figure></section><section class="card"><h2>準備開始</h2><p>請填寫自己的學習身分。</p><form id="identity"><div class="fields"><label>班級<input name="class" value="${esc(ident.class)}" required maxlength="20" placeholder="例如：701"></label><label>座號<input name="seat" value="${esc(ident.seat)}" required inputmode="numeric" maxlength="5" pattern="[0-9]{1,3}" placeholder="例如：12"></label><label>姓名<input name="name" value="${esc(ident.name)}" required maxlength="30" placeholder="請輸入姓名"></label></div><p class="small muted">更換任一欄位會開始新的學習紀錄。</p><button class="primary" type="submit">${state?'繼續我的探索':'開始我的探索'} →</button></form></section><section class="grid"><div class="card"><h3>第一次：生命、細胞與物質交換</h3><p>看見生命的線索 → 走進細胞世界 → 細胞的物質交換</p></div><div class="card"><h3>第二次：個體與大小世界</h3><p>從一個細胞到生命 → 世界的大小樣貌 → 理解檢查 → 救援與挑戰</p></div></section><div class="card blue"><h2>怎麼完成任務？</h2><p>先預測、再操作、記錄證據。答錯可以重試；學習分數與遊戲分數分開記錄。</p><p>${C.freeNavigation?'目前全課程開放，方便自由檢查。':'依序完成活動，即可開啟下一個任務。'}</p></div>${state?`<div class="card" id="homeProgress"><h3>我的進度</h3><progress max="10" value="${Object.keys(state.completed).length}"></progress><p>已完成 ${Object.keys(state.completed).length}／10 個單元 · 學習總分 ${total()}／75</p></div>`:''}`;
$('#identity').oninput=$('#identity').onchange=()=>{const f=new FormData($('#identity'));if(state&&['class','seat','name'].some(k=>f.get(k).trim()!==state.identity[k])){state=null;save();$('#homeProgress')?.remove();$('#identity button').textContent='開始我的探索 →';renderMap();toast('身分已更換，上一位學生的答案與分數已清除。');}};
$('#identity').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),identity=Object.fromEntries(['class','seat','name'].map(k=>[k,f.get(k).trim()]));if(!Object.values(identity).every(Boolean))return;if(!state)state=newState(identity);save();emit('start',{});location.hash='life';};}
function flashHTML(){return `<section class="card"><h2>閃卡關卡：複式顯微鏡</h2><p>先回想構造功能，再翻卡核對。不熟的卡片加入複習。</p><div id="flashArea"></div></section>`;}
function startFlash(){if(state?.flash){$('#flashArea').innerHTML='<p>✓ 已完成 13 張閃卡與待複習卡回顧。</p><button id="flashAgain">再複習一次</button>';$('#flashAgain').onclick=()=>{flashRun=null;showFlash(true);};return;}showFlash();}
function showFlash(force=false){if(!flashRun)flashRun={deck:shuffle(D.flash.map((_,i)=>i)),index:0,retry:[],phase:'first',flipped:false};const r=flashRun,idx=r.deck[r.index];if(idx===undefined){if(r.phase==='first'&&r.retry.length){r.deck=r.retry;r.index=0;r.phase='review';r.flipped=false;return showFlash();}if(requireStudent()){state.flash=true;save();if(pageReady('life'))complete('life');}$('#flashArea').innerHTML='<p>✓ 閃卡完成！接著操作顯微鏡，驗證你的理解。</p><button id="flashAgain">再複習一次</button>';$('#flashAgain').onclick=()=>{flashRun=null;showFlash(true);};return;}
const f=D.flash[idx];$('#flashArea').innerHTML=`<p class="small">${r.phase==='review'?'待複習卡回顧':'構造與功能'} · 第 ${r.index+1}／${r.deck.length} 張</p><button class="flash-card" id="flip" aria-label="${r.flipped?'翻回構造名稱':'翻卡查看功能'}"><strong>${f[0]}</strong><span>${r.flipped?f[1]:'它位在哪裡？有什麼功能？'}</span>${r.flipped?`<span class="small">${f[2]}</span>`:''}</button><div class="actions"><button id="retryCard" ${r.flipped?'':'disabled'}>還要練習</button><button id="knownCard" class="primary" ${r.flipped?'':'disabled'}>已經熟悉</button></div>`;$('#flip').onclick=()=>{r.flipped=!r.flipped;showFlash();};function next(retry){if(retry&&r.phase==='first')r.retry.push(idx);r.index++;r.flipped=false;showFlash();}$('#retryCard').onclick=()=>next(true);$('#knownCard').onclick=()=>next(false);}
function lesson(){const l=D.lessons[page];app.innerHTML=title(D.pages.find(p=>p[0]===page)[2],'概念 → 操作觀察 → 練習 → 修正與應用')+`<article class="lesson"><section class="card"><h2>先讀一個核心概念</h2><p>${esc(l.concept)}</p><label>${esc(l.sentence)}：<select id="keyword"><option value="">請選擇</option>${shuffle(l.keyword).map(x=>`<option>${x}</option>`).join('')}</select></label><p id="keywordFeedback" aria-live="polite"></p></section>${page==='life'?flashHTML():''}<section class="card"><h2>${{life:'探索：移動玻片，影像往哪裡走？',cell:'探索：比較植物與動物細胞',exchange:'探索：清水與鹽水會有什麼不同？',organism:'探索：把生命的層次連起來',scale:'探索：放大照片，實際大小會變嗎？'}[page]}</h2><div id="explore"></div></section>${l.reading?`<section class="card blue"><h2>${page==='cell'?'閱讀：細胞的發現':'閱讀：美味食材不浪費'}</h2><p>${l.reading}</p></section>`:''}<section><h2>換你證明理解</h2><p>完成作答後檢查。答對才完成；答錯可以重新作答。</p><div id="questions"></div></section></article><p class="score-tip">學習總分 <strong id="learningTotal">${total()}</strong>／75 · 首次答對 3 分，第二次 2 分，第三次起 1 分</p>${footerNav()}`;
$('#keyword').onchange=e=>$('#keywordFeedback').textContent=e.target.value===l.correctWord?'✓ 正確，接著用操作確認。':e.target.value?'再讀一次核心概念，想想關鍵字。':'';
if(page==='life')startFlash();explore();renderQuestions(l.questions);}
function opts(q){return orders[q.id]||(orders[q.id]=shuffle(q.options));}
function questionHTML(q,formal=false){const done=!formal&&state?.answers[q.id],f=!formal&&feedback[q.id];let input='';if(q.type==='order'){const order=draft[q.id]||(draft[q.id]=shuffle(q.options.map(x=>x.id)));input=order.map((id,i)=>`<div class="order-row"><span>${i+1}. ${esc(id)}</span><span><button type="button" data-move="${q.id}|${i}|-1" aria-label="${esc(id)}向上" ${done||i===0?'disabled':''}>↑</button><button type="button" data-move="${q.id}|${i}|1" aria-label="${esc(id)}向下" ${done||i===order.length-1?'disabled':''}>↓</button></span></div>`).join('');}
else if(['match','classify'].includes(q.type)){const choices=orders[q.id+'-values']||(orders[q.id+'-values']=shuffle([...new Set(Object.values(q.answer))]));input=opts(q).map(o=>`<label class="field">${esc(o.label)}<select data-q="${q.id}" data-key="${esc(o.id)}" ${done?'disabled':''}><option value="">請選擇</option>${choices.map(x=>`<option value="${esc(x)}" ${(done?state.answers[q.id]:draft[q.id])?.[o.id]===x?'selected':''}>${esc(x)}</option>`).join('')}</select></label>`).join('');}
else if(q.type==='number')input=`<label class="field">答案（微米）<input data-q="${q.id}" type="number" min="0" step="any" value="${esc(done?state.answers[q.id]:draft[q.id])}" ${done?'disabled':''}></label>`;
else if(q.type==='select')input=`<select data-q="${q.id}" aria-label="${esc(q.title)}" ${done?'disabled':''}><option value="">請選擇</option>${opts(q).map(o=>`<option value="${esc(o.id)}" ${(done?state.answers[q.id]:draft[q.id])===o.id?'selected':''}>${esc(o.label)}</option>`).join('')}</select>`;
else if(q.type==='label'){const points=[{id:'細胞壁',x:0,y:70,tx:12,ty:67},{id:'細胞膜',x:0,y:35,tx:18,ty:50},{id:'細胞核',x:80,y:30,tx:68,ty:38},{id:'液胞',x:35,y:0,tx:43,ty:35}];input=`<div style="position:relative;width:270px;max-width:100%;margin:15px auto"><img src="assets/plant-cell.png" alt="植物細胞模式圖，四個位置標示供選擇" style="width:100%;display:block"><svg viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true" style="position:absolute;inset:0;width:100%;height:100%;pointer-events:none">${points.map(p=>`<line x1="${p.x+6}" y1="${p.y+6}" x2="${p.tx}" y2="${p.ty}" stroke="#193f46" stroke-width=".6"/><circle cx="${p.tx}" cy="${p.ty}" r="1.1" fill="#193f46"/>`).join('')}</svg>${points.map((p,i)=>`<button data-label-q="${q.id}" data-answer="${p.id}" aria-label="構造位置 ${i+1}" style="position:absolute;left:${p.x}%;top:${p.y}%" ${done?'disabled':''} aria-pressed="${(done?state.answers[q.id]:draft[q.id])===p.id}">${i+1}</button>`).join('')}</div>`;}
else {const multi=q.type==='multi',a=done?state.answers[q.id]:draft[q.id];input=`<div class="choices">${opts(q).map(o=>`<label class="choice"><input data-q="${q.id}" type="${multi?'checkbox':'radio'}" name="${q.id}" value="${esc(o.id)}" ${(multi?a?.includes(o.id):a===o.id)?'checked':''} ${done?'disabled':''}>${esc(o.label)}</label>`).join('')}</div>`;}
const locked=done||f;return `<div id="q-${q.id}" class="card question ${done?'correct':f?'incorrect':''}"><fieldset ${locked&&!formal?'disabled':''}><legend>${esc(q.title)}</legend>${q.type==='multi'?'<p class="small">可選多個答案。</p>':''}${input}</fieldset>${formal?'':`<button class="primary check" data-check="${q.id}" ${locked||!filled(q,draft[q.id])?'disabled':''}>${done?'已完成':'檢查答案'}</button>${done||f?`<div class="feedback" role="status">${done?'✓ 答對了！':'再想一想。'} ${esc(q.explain)}</div>`:''}${f?`<button data-retry="${q.id}">重新作答</button>`:''}`}</div>`;}
function renderQuestions(qs){$('#questions').innerHTML=qs.map((q,i)=>`<p class="small muted">練習 ${i+1}／${qs.length}</p>${questionHTML(q)}`).join('');bindQuestions(qs);}
function bindQuestions(qs,formal=false){app.querySelectorAll('[data-q]').forEach(el=>el.onchange=()=>{const q=qs.find(x=>x.id===el.dataset.q);if(el.dataset.key){draft[q.id]||={};draft[q.id][el.dataset.key]=el.value;}else if(q.type==='multi')draft[q.id]=[...app.querySelectorAll(`[data-q="${q.id}"]:checked`)].map(x=>x.value);else draft[q.id]=el.value;const check=app.querySelector(`[data-check="${q.id}"]`);if(check)check.disabled=!filled(q,draft[q.id]);if(formal)$('#submitAssessment').disabled=!qs.every(x=>filled(x,draft[x.id]));});
app.querySelectorAll('[data-label-q]').forEach(b=>b.onclick=()=>{draft[b.dataset.labelQ]=b.dataset.answer;renderQuestions(qs);});
app.querySelectorAll('[data-move]').forEach(b=>b.onclick=()=>{let[id,i,delta]=b.dataset.move.split('|');i=+i;delta=+delta;[draft[id][i],draft[id][i+delta]]=[draft[id][i+delta],draft[id][i]];renderQuestions(qs);});
app.querySelectorAll('[data-check]').forEach(b=>b.onclick=()=>{if(!requireStudent())return;const q=qs.find(x=>x.id===b.dataset.check),a=draft[q.id];if(!filled(q,a)||state.answers[q.id])return;state.counts[q.id]=(state.counts[q.id]||0)+1;const correct=grade(q,a);if(correct){state.answers[q.id]=a;const points=Math.max(1,4-state.counts[q.id]);state.points[q.id]=points;toast(`＋${points} 分 · 目前學習總分 ${total()}／75`);}else feedback[q.id]=true;save();emit('attempt',{questionId:q.id,answer:a,attempt:state.counts[q.id],durationMs:Date.now()-quizStart});if(pageReady(page))complete(page);renderQuestions(qs);$('#learningTotal').textContent=total();});
app.querySelectorAll('[data-retry]').forEach(b=>b.onclick=()=>{delete feedback[b.dataset.retry];delete draft[b.dataset.retry];delete orders[b.dataset.retry];renderQuestions(qs);});}
function explore(){if(page==='life'){let x=0,y=0;$('#explore').innerHTML=`<p>先預測：玻片向右移，影像會向哪裡移？</p><div class="grid"><div class="activity"><div class="scope"><span id="scopeGlyph">DF</span></div><p id="scopeResult" aria-live="polite">影像在中央 · 總倍率 40 倍</p></div><div><label class="field">物鏡倍率<select id="magnification"><option value="4">4 倍</option><option value="10">10 倍</option><option value="40">40 倍</option></select></label><p>移動玻片</p><div class="actions">${[['←',-1,0],['↑',0,-1],['↓',0,1],['→',1,0]].map(a=>`<button data-slide="${a[1]},${a[2]}" aria-label="玻片往${a[0]}移">${a[0]}</button>`).join('')}</div><label class="field">亮度<input id="brightness" type="range" min="40" max="100" value="100"></label><label class="field">細調對焦<input id="focus" type="range" min="0" max="10" value="5"></label><button id="scopeReset">重新觀察</button></div></div><div class="evidence">比較：換高倍後影像變大、視野變小；複式影像與玻片移動方向相反。</div>`;function update(){const m=+$('#magnification').value;$('#scopeGlyph').style.transform=`translate(${-x*12}px,${-y*12}px) rotate(180deg) scale(${m/4})`;$('#scopeGlyph').style.filter=`blur(${Math.abs(5-$('#focus').value)}px)`;$('.scope').style.filter=`brightness(${$('#brightness').value}%)`;$('#scopeResult').textContent=`玻片位移（${x}，${y}）· 影像反向位移 · 總倍率 ${m*10} 倍`;}$('[data-slide]')?.parentElement.querySelectorAll('button').forEach(b=>b.onclick=()=>{const a=b.dataset.slide.split(',').map(Number);x+=a[0];y+=a[1];update();});['magnification','brightness','focus'].forEach(id=>$('#'+id).oninput=update);$('#scopeReset').onclick=()=>{x=y=0;$('#magnification').value=4;$('#focus').value=5;$('#brightness').value=100;update();};}
if(page==='cell'){$('#explore').innerHTML=`<p>先比對外圍、液胞與葉綠體，找出共同與不同的構造。</p><div class="image-pair"><figure><h3>植物細胞</h3><img data-zoom src="assets/plant-cell.png" alt="植物細胞模式圖：壁、膜、大液胞、核、葉綠體與粒線體"><figcaption class="small">含葉綠體的植物細胞模式圖</figcaption></figure><figure><h3>動物細胞</h3><img data-zoom src="assets/animal-cell.png" alt="動物細胞模式圖：膜、核、粒線體與小液胞"><figcaption class="small">動物細胞模式圖</figcaption></figure></div><div class="pills"><button data-structure="共同">共同構造</button><button data-structure="壁">細胞壁與膜</button><button data-structure="綠">葉綠體</button><button data-structure="液">液胞</button></div><div id="structureResult" class="evidence" aria-live="polite">點選構造，比對兩張圖中的位置與功能。</div><details><summary>觀察真實細胞：普通表皮與口腔細胞</summary><div class="image-pair"><figure><img data-zoom src="assets/epidermis.jpg" alt="鴨跖草表皮細胞影像"><figcaption>鴨跖草表皮</figcaption></figure><figure><img data-zoom src="assets/cheek.jpg" alt="口腔皮膜細胞影像"><figcaption>口腔皮膜細胞</figcaption></figure></div><p class="source">參考影像出自提供的翰林版教材圖檔。</p></details>`;const texts={'共同':'兩者都有細胞膜、細胞質、細胞核與粒線體。','壁':'植物細胞壁在細胞膜外側，提供支持；動物細胞沒有細胞壁。','綠':'葉綠體與光合作用有關；普通表皮細胞通常無葉綠體，保衛細胞有。','液':'此模式圖植物細胞有大液胞，動物細胞液胞較小。'};app.querySelectorAll('[data-structure]').forEach(b=>b.onclick=()=>{$('#structureResult').textContent=texts[b.dataset.structure];app.querySelectorAll('[data-structure]').forEach(x=>x.setAttribute('aria-pressed',x===b));});}
if(page==='exchange'){$('#explore').innerHTML=`<p>只改變外液條件，保持樣本及觀察時間相同。先預測，再開始觀察。</p><div class="grid"><div class="activity"><svg id="osmosis" class="diagram" viewBox="0 0 400 260" role="img" aria-label="細胞在不同外液中的水分移動模型"></svg><p id="waterResult" aria-live="polite"></p></div><div><label class="field">我的預測<select id="waterPrediction"><option value="">請選擇</option><option>細胞吸水</option><option>細胞失水</option><option>外形大致不變</option></select></label><label class="field">外液條件<select id="solution"><option value="fresh">清水</option><option value="same">與細胞內條件相近</option><option value="salt">濃鹽水</option></select></label><button id="waterRun" class="primary">開始觀察</button><p id="waterFeedback" class="evidence"></p></div></div>`;$('#waterRun').onclick=()=>{const v=$('#solution').value,correct={fresh:'細胞吸水',same:'外形大致不變',salt:'細胞失水'}[v];if(!$('#waterPrediction').value){toast('先選擇預測，再開始觀察。');return;}const size={fresh:88,same:72,salt:51}[v];$('#osmosis').innerHTML=`<rect x="80" y="25" width="240" height="205" rx="20" fill="#ecf4d8" stroke="#759065" stroke-width="8"/><ellipse cx="200" cy="128" rx="${size}" ry="${size}" fill="#9bd5e4" stroke="#147d78" stroke-width="3"/><text x="15" y="20" fill="#193f46" font-size="17">水分：${v==='fresh'?'向內 →':v==='salt'?'向外 →':'雙向移動'}</text>`;$('#waterResult').textContent=correct+'（示意模型）';$('#waterFeedback').textContent=($('#waterPrediction').value===correct?'預測與結果一致。':'結果與預測不同，再比較外液條件。')+'水分移動與內外條件有關，細胞壁與細胞內容物的變化不同。';};}
if(page==='organism'){$('#explore').innerHTML=`<p>切換動植物，看看哪些層次相同、哪些不同。</p><div class="actions"><button id="animalLevels">動物</button><button id="plantLevels">植物</button></div><div id="levels" class="pills"></div><p id="levelResult" class="evidence" aria-live="polite"></p><details><summary>水滴中的生命：比對單細胞與多細胞</summary><p>草履蟲和衣藻：一個細胞完成生命活動。水螅：不同細胞分工形成多細胞個體。</p><label>未知樣本只有一個細胞，但能游動與攝食：<select id="unknown"><option value="">請判斷</option><option>單細胞生物</option><option>多細胞生物</option></select></label><p id="unknownFeedback"></p></details>`;function levels(plant){$('#levels').innerHTML=(plant?['細胞','組織','器官','個體']:['細胞','組織','器官','系統','個體']).map(x=>`<button>${x}</button>`).join('');$('#levelResult').textContent=plant?'植物的器官包括根、莖、葉；依教材不使用系統層次。':'動物的器官組成系統，不同系統協調運作。';}$('#animalLevels').onclick=()=>levels(false);$('#plantLevels').onclick=()=>levels(true);levels(false);$('#unknown').onchange=e=>$('#unknownFeedback').textContent=e.target.value==='單細胞生物'?'✓ 以細胞數與生命功能判斷。':'再看細胞數，不以會不會游動判斷。';}
if(page==='scale'){$('#explore').innerHTML=`<p>樣本與比例尺一起縮放。先推算實長，再調整照片大小。</p><svg class="diagram" viewBox="0 0 500 220" role="img" aria-label="眼蟲示意與比例尺，眼蟲長度為比例尺的三倍"><g id="scaledSpecimen"><ellipse cx="250" cy="80" rx="135" ry="28" fill="#93bd84" stroke="#587950" stroke-width="3"/><circle cx="145" cy="75" r="6" fill="#c56849"/><path d="M385 80 Q420 60 439 90" fill="none" stroke="#587950" stroke-width="3"/><path d="M115 150 H205 M115 143 V157 M205 143 V157" stroke="#193f46" stroke-width="4"/><text x="115" y="185" font-size="18" fill="#193f46">25 微米</text></g></svg><label class="field">照片縮放：<span id="zoomValue">100％</span><input id="scaleZoom" type="range" min="60" max="120" value="100"></label><label>樣本長度是比例尺的幾倍？<select id="scaleRatio"><option value="">請選擇</option><option>2 倍</option><option>3 倍</option><option>4 倍</option></select></label><p id="ratioFeedback" class="evidence" aria-live="polite">照片變大，實際大小會改變嗎？</p>`;$('#scaleZoom').oninput=e=>{const s=e.target.value/100;$('#scaledSpecimen').setAttribute('transform',`translate(${250*(1-s)},${100*(1-s)}) scale(${s})`);$('#zoomValue').textContent=e.target.value+'％';};$('#scaleRatio').onchange=e=>$('#ratioFeedback').textContent=e.target.value==='3 倍'?'✓ 3 × 25＝75 微米。一起縮放後，比值不變。':'比較樣本的主體長度與比例尺，不計鞭毛。';}}
function assessment(){if(state?.formative!==null&&state){app.innerHTML=title('我的理解檢查')+`<div class="card soft"><h2>首次正式成績：${state.formative}／100</h2><p>已完成，首次結果會保留。回到學習頁可以修正觀念。</p></div>${D.formative.map(q=>`<details class="card"><summary>${esc(q.title)}</summary><p>${esc(q.explain)}</p></details>`).join('')}${footerNav()}`;return;}
app.innerHTML=title('我的理解檢查','共 10 題，全部作答後統一提交；不需要全對才完成。')+`<p class="source">題目依提供的翰林版生命習題與跨科習題改寫。</p><div id="questions">${D.formative.map((q,i)=>`<p>第 ${i+1} 題</p>${q.id==='F10'?'<svg class="diagram" viewBox="0 0 400 160" role="img" aria-label="眼蟲與 25 微米比例尺示意圖"><ellipse cx="190" cy="55" rx="135" ry="32" fill="#d9efc5" stroke="#147d78" stroke-width="3"/><circle cx="85" cy="50" r="7" fill="#cf684c"/><path d="M325 55 Q355 10 370 55" fill="none" stroke="#147d78" stroke-width="2"/><line x1="55" y1="115" x2="145" y2="115" stroke="#193f46" stroke-width="4"/><text x="70" y="145" font-size="18">25 微米</text></svg>':''}${questionHTML(q,true)}`).join('')}</div><button id="submitAssessment" class="primary" disabled>提交全部答案</button>${footerNav()}`;bindQuestions(D.formative,true);$('#submitAssessment').onclick=()=>{if(!requireStudent()||!D.formative.every(q=>filled(q,draft[q.id])))return;const answers=Object.fromEntries(D.formative.map(q=>[q.id,draft[q.id]]));state.formative=D.formative.reduce((n,q)=>n+(grade(q,answers[q.id])?10:0),0);save();emit('formative',{answers,durationMs:Date.now()-quizStart});complete('assessment');render();toast(`理解檢查 ${state.formative} 分 · 首次結果已保留`);};}
function rescue(){app.innerHTML=title('細胞救援任務','6 次救援：看線索、做決策、修復問題。')+`<div class="card soft"><p>每關首次答對 100 分；答錯後看解析再修復，不再加分。</p><button id="startRescue" class="primary">開始救援</button></div><div id="rescueArea"></div>${footerNav()}`;$('#startRescue').onclick=()=>{if(!requireStudent())return;rescueRun={i:0,score:0,wrong:false,answers:[]};rescueStep();};}
function rescueStep(){const r=rescueRun;if(r.i===D.rescue.length){state.rescueFirst??=r.score;state.rescueBest=Math.max(state.rescueBest,r.score);save();emit('rescue',{score:r.score,answers:r.answers});complete('rescue');$('#rescueArea').innerHTML=`<div class="card correct"><h2>救援完成！${r.score}／600 分</h2><p>首次 ${state.rescueFirst} 分 · 最高 ${state.rescueBest} 分</p><button id="againRescue">再挑戰</button></div>`;$('#againRescue').onclick=()=>$('#startRescue').click();return;}const q=D.rescue[r.i],labels=q.type==='multi'?[q.answer.join('、'),'只有細胞核','只有形狀像方形']:q.type==='number'?['25','75','125']:shuffle(q.options.map(x=>x.id));$('#rescueArea').innerHTML=`<div class="card"><p class="chip">任務 ${r.i+1}／6 · 得分 ${r.score}</p><h2>${esc(q.title)}</h2><div class="choices">${labels.map(x=>`<button data-rescue="${esc(x)}">${esc(x)}</button>`).join('')}</div><p id="rescueFeedback" role="status"></p></div>`;app.querySelectorAll('[data-rescue]').forEach(b=>b.onclick=()=>{const a=q.type==='multi'?b.dataset.rescue.split('、'):b.dataset.rescue,ok=grade(q,a);r.answers.push({questionId:q.id,answer:a,first:!r.wrong});if(ok){if(!r.wrong)r.score+=100;$('#rescueFeedback').textContent='✓ 修復成功！'+q.explain;app.querySelectorAll('[data-rescue]').forEach(x=>x.disabled=true);const next=document.createElement('button');next.className='primary';next.textContent='繼續救援 →';next.onclick=()=>{r.i++;r.wrong=false;rescueStep();};$('#rescueFeedback').after(next);}else{r.wrong=true;$('#rescueFeedback').textContent='再想一想。'+q.explain;}});}
function challenge(){app.innerHTML=title('生命極限挑戰','20 題，3 次生命。越快答對，分數越高。')+`<div class="card soft"><p>答錯扣 1,000 分及一次生命；逾時扣生命。答對單題最高 5,000 分。</p><button id="startChallenge" class="primary">開始挑戰</button></div><div id="challengeArea"></div>${footerNav()}`;$('#startChallenge').onclick=()=>{if(!requireStudent())return;challengeRun={items:shuffle(D.challenge),i:0,score:0,lives:3,answers:[],locked:false};challengeStep();};}
function challengeStep(){clearInterval(timer);const r=challengeRun;if(!r)return;if(r.i>=r.items.length||r.lives<=0){state.challengeFirst??=r.score;state.challengeBest=Math.max(state.challengeBest,r.score);save();emit('challenge',{score:r.score,answers:r.answers});complete('challenge');$('#challengeArea').innerHTML=`<div class="card soft"><h2>挑戰結束！${r.score.toLocaleString()} 分</h2><p>首次 ${state.challengeFirst.toLocaleString()} · 最高 ${state.challengeBest.toLocaleString()}</p><button id="challengeAgain">再挑戰</button></div><div class="card"><h2>全體英雄榜 · 前 10 名</h2><div id="leaderboard">正在讀取排行榜……</div></div>`;$('#challengeAgain').onclick=()=>$('#startChallenge').click();leaderboard();return;}const q=r.items[r.i],speed=.35+r.i*.015,limit=100/speed*20;r.started=performance.now();r.locked=false;$('#challengeArea').innerHTML=`<div class="card"><div class="statusline"><strong>第 ${r.i+1}／20 題</strong><strong class="lives">生命 ${'●'.repeat(r.lives)}${'○'.repeat(3-r.lives)}</strong><strong>分數 ${r.score.toLocaleString()}</strong></div><p>${esc(q.title)}</p><div class="track"><span class="runner">${esc(q.title)}</span></div><p id="timeLeft" class="mono" role="timer"></p><div class="choices">${shuffle(q.options).map(o=>`<button data-fast="${esc(o.id)}">${esc(o.label)}</button>`).join('')}</div><p id="challengeFeedback" role="status"></p></div>`;function answer(a,timeout=false){if(r.locked)return;r.locked=true;clearInterval(timer);const ms=Math.round(performance.now()-r.started),pos=Math.min(100,ms/20*speed),ok=!timeout&&grade(q,a);if(ok)r.score+=Math.max(500,Math.floor(5000-pos*45));else{if(!timeout)r.score=Math.max(0,r.score-1000);r.lives--;}r.answers.push({questionId:q.id,answer:a??'',durationMs:Math.round(ms),timeout});$('#challengeFeedback').textContent=(ok?'✓ 答對！':timeout?'時間到。':'再想一想。')+q.explain;app.querySelectorAll('[data-fast]').forEach(b=>b.disabled=true);const next=document.createElement('button');next.className='primary';next.textContent='下一個目標 →';next.onclick=()=>{r.i++;challengeStep();};$('#challengeFeedback').after(next);}app.querySelectorAll('[data-fast]').forEach(b=>b.onclick=()=>answer(b.dataset.fast));timer=setInterval(()=>{const ms=performance.now()-r.started,p=Math.min(100,ms/limit*100);$('.runner').style.left=`calc(${p}% - ${p*1.8}px)`;$('#timeLeft').textContent=`剩餘 ${Math.max(0,(limit-ms)/1000).toFixed(1)} 秒`;if(ms>=limit)answer('',true);},40);}
function leaderboard(){if(!C.gasUrl){$('#leaderboard').textContent='尚未連接全體英雄榜；你的成績已保存在此裝置。';return;}const cb='scienceBoard_'+Date.now(),script=document.createElement('script');const timeout=setTimeout(()=>{delete window[cb];script.remove();if($('#leaderboard'))$('#leaderboard').textContent='目前無法讀取排行榜，請稍後再試。';},12000);window[cb]=data=>{clearTimeout(timeout);delete window[cb];script.remove();if(!$('#leaderboard'))return;$('#leaderboard').innerHTML=data.entries?.length?`<div class="table-wrap"><table><thead><tr><th>排名</th><th>匿名代稱</th><th>最高分</th></tr></thead><tbody>${data.entries.map((r,i)=>`<tr><td>${i+1}</td><td>${esc(r.alias)}</td><td>${Number(r.score).toLocaleString()}</td></tr>`).join('')}</tbody></table></div>`:'目前尚無排行榜成績。';};script.src=C.gasUrl+'?action=leaderboard&callback='+cb;document.body.append(script);}
function results(){const n=Object.keys(state?.completed||{}).filter(x=>x!=='results').length;if(state&&n===9&&!state.completed.results)complete('results');app.innerHTML=title('我的學習成果','看看你找到哪些證據，還能再探索什麼。')+`<div class="card soft"><h2>${state?esc(state.identity.name)+'，':''}你的探索紀錄</h2><progress max="10" value="${Object.keys(state?.completed||{}).length}"></progress><p>完成 ${Object.keys(state?.completed||{}).length}／10 個單元</p></div><div class="stats">${[['學習總分',total()+'／75','五個學習頁'],['理解檢查',state?.formative===null||!state?'尚未完成':state.formative+'／100','首次正式結果'],['細胞救援',(state?.rescueBest||0)+'／600','首次 '+(state?.rescueFirst??'尚未完成')],['極限挑戰',(state?.challengeBest||0).toLocaleString(),'首次 '+(state?.challengeFirst??'尚未完成')]].map(a=>`<div class="card"><h3>${a[0]}</h3><p class="stat-value">${a[1]}</p><p class="small muted">${a[2]}</p></div>`).join('')}</div><div class="card"><h2>回顧與重學</h2>${Object.keys(D.lessons).map(id=>`<div class="actions"><span>${state?.completed[id]?'✓':'○'} ${D.pages.find(p=>p[0]===id)[2]}</span><button data-nav="${id}">重學</button></div>`).join('')}</div><div class="card blue"><h2>學習紀錄</h2><p id="syncState"></p><button id="retrySync">再次同步</button><button id="downloadRecord">下載自己的學習紀錄</button></div><div class="nav-end"><button class="primary" data-nav="home">回到首頁</button></div>`;showSync();$('#retrySync').onclick=()=>sync();$('#downloadRecord').onclick=()=>{if(!requireStudent())return;const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='我的生命探索紀錄.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};}
function showSync(){if(!$('#syncState'))return;const pending=queue.filter(x=>x.session===state?.session).length;$('#syncState').textContent=!C.gasUrl?'紀錄已保存在此裝置；尚未連接教師回應表。':pending?`${pending} 筆紀錄等待同步；保持連線後可再次同步。`:'紀錄已送達教師回應表。';}
async function sync(){if(sending||!queue.length||!C.gasUrl)return;const event=queue[0];sending=true;try{await sendToGas(event);queue=queue.filter(x=>x.requestId!==event.requestId);write('science-queue',queue);}catch(e){console.info('Response collection pending:',e.message);}finally{sending=false;showSync();}if(queue.length&&queue[0].requestId!==event.requestId)sync();}
function sendToGas(event){return new Promise((resolve,reject)=>{const frame=document.createElement('iframe'),form=document.createElement('form');frame.name='response_'+event.requestId.replaceAll('-','');frame.hidden=true;form.hidden=true;form.method='POST';form.action=C.gasUrl;form.target=frame.name;const input=document.createElement('input');input.name='payload';input.value=JSON.stringify(event);form.append(input);document.body.append(frame,form);const timeout=setTimeout(()=>done(new Error('未收到收件確認')),20000);function done(error){clearTimeout(timeout);window.removeEventListener('message',receive);frame.remove();form.remove();error?reject(error):resolve();}function receive(e){if(!/^https:\/\/(script\.google\.com|[a-z0-9-]+\.googleusercontent\.com)$/.test(e.origin))return;if(e.data?.type==='science-response'&&e.data.requestId===event.requestId)done(e.data.ok?null:new Error(e.data.error||'收集失敗'));}window.addEventListener('message',receive);form.submit();});}
window.addEventListener('online',sync);window.addEventListener('hashchange',route);$('#teacher').onclick=()=>$('#teacherDialog').showModal();$('#teacherUnlock').onclick=()=>{if($('#teacherPassword').value==='5506881'){teacher=true;$('#teacherDialog').close();renderMap();render();toast('已開放全課程自由檢查。');}else $('#teacherError').textContent='密碼不正確，請重新輸入。';};$('#closeZoom').onclick=()=>$('#zoom').close();route();sync();
})();

